package com.lms.userservice.domain.model;

import java.time.Instant;
import java.util.UUID;

/**
 * UserProfile — the aggregate root for the user domain.
 *
 * <p>Deliberately separate from auth-service's User entity.
 * Auth-service owns: credentials, roles, token lifecycle.
 * User-service owns: profile data, preferences, enrollment history references.
 *
 * <p>The userId is the shared identifier across both services —
 * it's the UUID generated by auth-service on registration.
 */
public class UserProfile {

    private final UUID userId;         // Shared key — same as auth-service user ID
    private String email;              // Denormalized from auth-service (read-only here)
    private String firstName;
    private String lastName;
    private String bio;
    private String avatarUrl;
    private String role;               // Denormalized from auth-service
    private ProfileStatus status;
    private Instant createdAt;
    private Instant updatedAt;

    public enum ProfileStatus {
        ACTIVE, SUSPENDED, DELETED
    }

    // ── Construction ────────────────────────────────────────

    private UserProfile(UUID userId, String email, String firstName,
                        String lastName, String role) {
        this.userId = userId;
        this.email = email;
        this.firstName = firstName;
        this.lastName = lastName;
        this.role = role;
        this.status = ProfileStatus.ACTIVE;
        this.createdAt = Instant.now();
        this.updatedAt = Instant.now();
    }

    /**
     * Creates a new profile — triggered by UserRegisteredEvent consumption.
     * The userId comes from auth-service to maintain consistency.
     */
    public static UserProfile create(UUID userId, String email,
                                     String firstName, String lastName, String role) {
        if (userId == null) throw new IllegalArgumentException("userId must not be null");
        if (email == null || email.isBlank()) throw new IllegalArgumentException("email must not be blank");
        return new UserProfile(userId, email, firstName, lastName, role);
    }

    public static UserProfile reconstitute(UUID userId, String email, String firstName,
                                            String lastName, String bio, String avatarUrl,
                                            String role, ProfileStatus status,
                                            Instant createdAt, Instant updatedAt) {
        UserProfile profile = new UserProfile(userId, email, firstName, lastName, role);
        profile.bio = bio;
        profile.avatarUrl = avatarUrl;
        profile.status = status;
        profile.createdAt = createdAt;
        profile.updatedAt = updatedAt;
        return profile;
    }

    // ── Business Behaviour ───────────────────────────────────

    public void updateProfile(String firstName, String lastName, String bio, String avatarUrl) {
        if (this.status == ProfileStatus.DELETED) {
            throw new IllegalStateException("Cannot update a deleted profile");
        }
        this.firstName = firstName;
        this.lastName = lastName;
        this.bio = bio;
        this.avatarUrl = avatarUrl;
        this.updatedAt = Instant.now();
    }

    public void suspend() {
        this.status = ProfileStatus.SUSPENDED;
        this.updatedAt = Instant.now();
    }

    public void reactivate() {
        if (this.status == ProfileStatus.DELETED) {
            throw new IllegalStateException("Cannot reactivate a deleted profile");
        }
        this.status = ProfileStatus.ACTIVE;
        this.updatedAt = Instant.now();
    }

    public void markDeleted() {
        this.status = ProfileStatus.DELETED;
        this.updatedAt = Instant.now();
    }

    public boolean isActive() {
        return this.status == ProfileStatus.ACTIVE;
    }

    public String fullName() {
        return firstName + " " + lastName;
    }

    // ── Getters ──────────────────────────────────────────────

    public UUID getUserId() { return userId; }
    public String getEmail() { return email; }
    public String getFirstName() { return firstName; }
    public String getLastName() { return lastName; }
    public String getBio() { return bio; }
    public String getAvatarUrl() { return avatarUrl; }
    public String getRole() { return role; }
    public ProfileStatus getStatus() { return status; }
    public Instant getCreatedAt() { return createdAt; }
    public Instant getUpdatedAt() { return updatedAt; }
}
