# ============================================================
# USER SERVICE — DEV PROFILE overrides
# ============================================================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/lms_users
  rabbitmq:
    host: localhost
